version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
  # Maintain dependencies for dockerfiles
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/tests"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      python:
        patterns:
          - "*"
