pull_request_rules:
  - name: approve dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - status-success=Travis CI - Pull Request
    actions:
      review:
        type: APPROVE

  - name: comment to start codebuild jobs
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: go codebuild go

  - name: comment to start vagrant job
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: go vagrant go

  - name: merge dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - "#approved-reviews-by>=1"
      # Must pass codebuild jobs before merge
      - status-success=codebuild/spel-ci/pr
      - status-success=codebuild/spel-govcloud-ci/pr
      - status-success=codebuild/spel-vagrant-ci/pr
    actions:
      merge:
        method: merge
