dist: focal

language: minimal

if: branch = master OR type = pull_request

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      install: make -f Makefile.tardigrade-ci install
      script: make -f Makefile.tardigrade-ci lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/spel
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [SPEL v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/spel/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: SxBWbiOc8wELixxH+CYzoBHIvqP9Iq85seo4rO3rPfTDld0IWDRSYlLOCXL7fujKAPmNbv1nICX9VPVOyMvjdeUY3RLJ2LIqkEm9fRieuZr8CzbROszmeLHhHl8hD4m8Adkg1QHo+fqNgzvjldPD0YDwbqbFFB5hXzSMu603D6qM/ymyZqCMF/F3DBdYhDN/xu6a32b9vSeochC1YrbucQXXZA8wE/pHmBqHQ0s9gRIkdBP3OgLaWb8wpoNJ8IzTBi7KdAyDs5plqMtjA1n/pUJKZ8WI5S59LMyFDwP2BUwVxQR5LddwGS2UEsFLjmCuB9H9NT7T2nAbbFVrlOmzCgCW6AvMCK3meEwpFsitJv/MYe6XRqkCFrSNPLrdp3Pa4gOX+rQUD7jRwXB4M8Fk12/fJbIdZbjFDsSWN2+zG9MoiNQJPTJs/oyvZsL1Xp/ab1GaggJDiAoVKHPenbDgIKjIYp+uxRPLGGT1/CTzth3D+D6pdgnCaETUFyIZot+OkLzSWj5atyFPQfqnxDiDNmMYKHDjjaYFLHAbLdVjP2RYQHJmdOYXtGrQQ8KEs0IJy2y8LXD+XFOvHwh0zm79+d7G6l18gVymdrYXO09/ctUK/vWPbhYelllurq+kttESMO0srDRe5Kadyh6gdEng1xm2qrX0OAHAl4qVL6tOE4Q=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/spel
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
