dist: focal

language: python
python: "3.10"

if: branch = master OR type = pull_request

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      install:
        - pip install -r tests/requirements.txt
        - make -f Makefile.tardigrade-ci lint/install
      script: make -f Makefile.tardigrade-ci lint
    - stage: deploy
      if: branch = master AND type = push AND repo = MetroStar/spel
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [SPEL v$RELEASE_VERSION CHANGELOG](https://github.com/MetroStar/spel/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        # Per https://travis-ci.community/t/deployments-are-failing-due-to-uri-dependency/14375
        - yes | gem update --system --force
        - gem install bundler
        # Travis-CI is so broken, https://travis-ci.community/t/cannot-load-such-file-faraday-net-http-loaderror/14455
        - gem install faraday-net_http -v '3.3.0'  # Fix faraday version
        - gem install uri
        - gem install logger
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key: $GH_RELEASES_TOKEN
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: MetroStar/spel
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
