#!/bin/bash
# Bootstrap OpenTofu S3 + DynamoDB backend for SSM infrastructure module
# Usage: source bootstrap-backend.sh [OPTIONS]
#
# This script idempotently creates the S3 bucket and DynamoDB table needed
# for the OpenTofu remote backend, then generates a backend.tf file.
# Designed to be called from CI/CD pipelines (GitHub Actions, GitLab CI)
# before `tofu init`.
#
# Options:
#   --prefix PREFIX     Resource name prefix (default: chimera-offline)
#   --region REGION     AWS region (default: $AWS_DEFAULT_REGION or us-east-1)
#   --bucket NAME       Override S3 bucket name (default: ${PREFIX}-ssm-tfstate-${ACCOUNT_ID})
#   --table NAME        Override DynamoDB table name (default: ${PREFIX}-ssm-tflock)
#   --key PATH          State file key path (default: ssm-infra/opentofu.tfstate)
#
# After running, an auto-generated backend.tf will be present in the current
# directory. The script also exports:
#   TF_BACKEND_BUCKET   - S3 bucket name
#   TF_BACKEND_TABLE    - DynamoDB table name
#   TF_BACKEND_REGION   - Region
#   TF_BACKEND_KEY      - State file key
#
# Safe to run repeatedly — all operations are idempotent.

set -euo pipefail

# Defaults
PREFIX="${INFRA_PREFIX:-chimera-offline}"
REGION="${AWS_DEFAULT_REGION:-${AWS_REGION:-us-east-1}}"
BUCKET_OVERRIDE=""
TABLE_OVERRIDE=""
STATE_KEY="ssm-infra/opentofu.tfstate"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --region) REGION="$2"; shift 2 ;;
    --bucket) BUCKET_OVERRIDE="$2"; shift 2 ;;
    --table)  TABLE_OVERRIDE="$2"; shift 2 ;;
    --key)    STATE_KEY="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: source $0 [--prefix PREFIX] [--region REGION] [--bucket NAME] [--table NAME] [--key PATH]"
      return 0 2>/dev/null || exit 0
      ;;
    *) echo "Unknown option: $1"; return 1 2>/dev/null || exit 1 ;;
  esac
done

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

# Derive names from prefix + account (ensures uniqueness per account)
BUCKET="${BUCKET_OVERRIDE:-${PREFIX}-ssm-tfstate-${ACCOUNT_ID}}"
TABLE="${TABLE_OVERRIDE:-${PREFIX}-ssm-tflock}"

echo "=== Bootstrapping OpenTofu Backend ==="
echo "  Region:  $REGION"
echo "  Bucket:  $BUCKET"
echo "  Table:   $TABLE"
echo "  Key:     $STATE_KEY"
echo ""

# -------------------------------------------------------------------------
# 1. Create S3 bucket if it does not exist
# -------------------------------------------------------------------------
if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "[OK] S3 bucket already exists: $BUCKET"
else
  echo "Creating S3 bucket: $BUCKET ..."

  # LocationConstraint is required for regions other than us-east-1
  if [[ "$REGION" == "us-east-1" ]]; then
    aws s3api create-bucket \
      --bucket "$BUCKET" \
      --region "$REGION"
  else
    aws s3api create-bucket \
      --bucket "$BUCKET" \
      --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=${REGION}"
  fi

  echo "[OK] Created S3 bucket"
fi

# Enable versioning (idempotent)
aws s3api put-bucket-versioning \
  --bucket "$BUCKET" \
  --versioning-configuration Status=Enabled \
  --region "$REGION"
echo "[OK] Versioning enabled"

# Enable default encryption (idempotent)
aws s3api put-bucket-encryption \
  --bucket "$BUCKET" \
  --region "$REGION" \
  --server-side-encryption-configuration '{
    "Rules": [{
      "ApplyServerSideEncryptionByDefault": {
        "SSEAlgorithm": "AES256"
      },
      "BucketKeyEnabled": true
    }]
  }'
echo "[OK] Encryption enabled"

# Block public access (idempotent)
aws s3api put-public-access-block \
  --bucket "$BUCKET" \
  --region "$REGION" \
  --public-access-block-configuration \
    BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
echo "[OK] Public access blocked"

# -------------------------------------------------------------------------
# 2. Create DynamoDB table if it does not exist
# -------------------------------------------------------------------------
if aws dynamodb describe-table --table-name "$TABLE" --region "$REGION" &>/dev/null; then
  echo "[OK] DynamoDB table already exists: $TABLE"
else
  echo "Creating DynamoDB table: $TABLE ..."
  aws dynamodb create-table \
    --table-name "$TABLE" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$REGION" \
    --tags Key=Project,Value=CHIMERA Key=ManagedBy,Value=opentofu-bootstrap >/dev/null

  echo "Waiting for table to become active..."
  aws dynamodb wait table-exists --table-name "$TABLE" --region "$REGION"
  echo "[OK] Created DynamoDB table"
fi

# -------------------------------------------------------------------------
# 3. Generate backend.tf in the current directory
# -------------------------------------------------------------------------
cat > backend.tf <<EOF
# Auto-generated by bootstrap-backend.sh — do not edit manually
# To regenerate: source bootstrap-backend.sh --prefix $PREFIX --region $REGION
terraform {
  backend "s3" {
    bucket         = "$BUCKET"
    key            = "$STATE_KEY"
    region         = "$REGION"
    encrypt        = true
    dynamodb_table = "$TABLE"
  }
}
EOF
echo "[OK] Generated backend.tf"

# -------------------------------------------------------------------------
# 4. Export variables for downstream use
# -------------------------------------------------------------------------
export TF_BACKEND_BUCKET="$BUCKET"
export TF_BACKEND_TABLE="$TABLE"
export TF_BACKEND_REGION="$REGION"
export TF_BACKEND_KEY="$STATE_KEY"

echo ""
echo "=== OpenTofu Backend Ready ==="
echo "  Run:  tofu init -input=false"
echo ""
